title: Kerry.Yang
description:  CFA I, FRM II
show_downloads: false
google_analytics:
index.md: 
github:
  is_project_page: false
kramdown:
  footnote_nr: 1
  auto_ids: false
collections:
  posts:
    output: false
theme: jekyll-theme-dinky

 
