title: Kerry.Yang
description:  CFA I, FRM II
show_downloads: false
google_analytics:
index.md: 
avatar: /images/img.jpg
github:
  is_project_page: false
  repository_url: https://github.com/YangQingQingKerry
  
kramdown:
  footnote_nr: 1
  
plugins:
  - jekyll-feed
   
 
theme: jekyll-theme-dinky

 
